# Generated by Django 4.2.5 on 2023-09-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
