# Generated by Django 4.2.5 on 2023-09-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_stock_order_date_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
    ]
